// gui_ids.h

#ifndef GUI_IDS_H
#define GUI_IDS_H

enum
{
  WINDOW_BUTTON_OK,
  WINDOW_BUTTON_1,
  WINDOW_BUTTON_2,
  WINDOW_BUTTON_3,
  WINDOW_BUTTON_4,
  WINDOW_COMBO_BOX_1,
  WINDOW_COMBO_BOX_2,
  WINDOW_COMBO_BOX_3,
  WINDOW_COMBO_BOX_4,
  WINDOW_COMBO_CHOICE_0,
  WINDOW_COMBO_CHOICE_1,
  WINDOW_COMBO_CHOICE_2,
  WINDOW_COMBO_CHOICE_3,
  WINDOW_COMBO_CHOICE_4,
  WINDOW_COMBO_CHOICE_5,
  WINDOW_COMBO_CHOICE_6,
  WINDOW_COMBO_CHOICE_7,
  WINDOW_COMBO_CHOICE_8,
  WINDOW_COMBO_CHOICE_9,

  MENU_NEW_GAME,
  MENU_QUIT,
  MENU_ABOUT
};

#endif
